AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "search-photos-from-pipeline"
      Handler: index.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: "Lambda function for search photo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::315539653047:role/service-role/index-photos-role-4aq5jjuv"
      Environment:
        Variables:
          REGION: us-east-1