AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index-photos.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::805107066630:role/service-role/index-photos-role-xxb6jqav'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
  Bucket1:
    Type: 'AWS::S3::Bucket'